### PR TITLE
feat(cli): added corresponding npm env variables

### PR DESCRIPTION
**Pull request by matthewdordal**
A few instances of Drone I have seen use environmental variables such as `NPM_EMAIL` and `NPM_REGISTRY`. This PR adds an `NPM_*` version of the `PLUGIN_*` variables that did not already have a corresponding npm variable.

Please let me know if you need anything else from this PR. This is the first time I've run across Go so if I missed a test that needs to be updated let me know.

### CODE REVIEW

**Comment by donny-dont** [comment]
Is there a reason why you're adding these? Typically we expose certain values as secrets and I don't see why any of these would be secrets

**Comment by bradrydzewski** [comment]
My guess would be that developers are setting these as environment variables, not knowing there are corresponding yaml attributes. But just a guess.

**Comment by matthewdordal** [comment]
@donny-dont it seemed inconsistent to allow some NPM_* variables but not others. `PLUGIN_TAG` seemed like one that would be used as an npm config as well. 

This may be an irrelevant PR. I just ran across it in a _.drone.yml_ that was using *NPM_FOLDER* and that seemed to be ignored. If I misunderstood the point of those PLUGIN_* variables I apologice and can close the PR.

**Comment by donny-dont** [comment]
@matthewdordal so a Droneism with those values is that typically if something should be a secret we expose the FOO_VALUE in the CLI so it will pick it up as an environment variable.

```
  npm-publish:
    folder: foo
```

Is typically how those things are done

**Comment by matthewdordal** [comment]
@donny-dont thanks! I'll close the PR then. I didn't realize some of these were intentionally secrets.

**Comment by donny-dont** [comment]
@matthewdordal thanks for the PR! Always appreciate new contributors. Hopefully this helps you in writing your own plugins in the future.

**Pull request closed without merging**
