### PR TITLE
Allow for Hosts to have paths with tokens

### PR DESCRIPTION
**Pull request by sclm**
This changes the config from only passing the host through to allowing for the inclusion of a path with it.

### CODE REVIEW

**Comment by bradrydzewski** [comment]
@donny-dont I believe this is required for when the registry has a base URL path.  This look good to you?

**Comment by donny-dont** [comment]
With it setting the scheme it looks fine and tests are good.

@sclm just curious what NPM provider requires this?

**Comment by sclm** [comment]
@donny-dont _require_ is a strong term, but our setup for Artifactory is what ended up wanting this. My belief is that we could work with a URL rewrite to add the path on with a different hostname, but that's not required by the `npm` cli, so we didn't want to require it.

**Comment by donny-dont** [comment]
@sclm thank you!

**Pull request merged**
