### PR TITLE
Streamline, proper documentation, cleanup

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by donny-dont** [comment]
I'm good with this. Just wondering if we should rip out the instructions on how to build the Dockerfile.

**Comment by tboerger** [comment]
It's not ripped out, it's just formatted differently :)

**Comment by donny-dont** [comment]
LGTM

**Comment by bradrydzewski** [comment]
what vendoring tool is this using? this is a big increase in file size

**Comment by bradrydzewski** [comment]
maybe the difference is that I am using govendor which only vendors dependencies in the local cache, and I don't have `golang.org/x/sys` installed local cache because it is only required by the `+build solaris` tag in logrus?

**Comment by bradrydzewski** [comment]
also do we _need_ the vendor.yml file? one less file in the root would be nice, unless there is a compelling reason to start adding it. I've been omitting them

**Comment by tboerger** [comment]
> also do we need the vendor.yml file? one less file in the root would be nice, unless there is a compelling reason to start adding it. I've been omitting them

This is the only way with govend to see which version we currently rely on.

**Comment by tboerger** [comment]
@bradrydzewski I have applied all comments from the streamline PRs.

**Comment by donny-dont** [comment]
LGTM

**Comment by Bugagazavr** [comment]
LGTM

**Pull request merged**
