### PR TITLE
Update to use drone-plugin-lib

### PR DESCRIPTION
**Pull request by donny-dont**
This updates the `drone-npm` plugin to use the `drone-plugin-lib` and the `boilr-plugin` for scaffolding.

### CODE REVIEW

**Comment by donny-dont** [comment]
Don't merge yet but if either of you could take a look at it its appreciated. Still trying to finalize the `boilr-plugin` templates and I want to verify those fit before merging.

**Comment by tboerger** [comment]
Let's get the boilr template and the plugin lib better sorted out before. We should also make it more idiomatic for Go libraries.

**Comment by donny-dont** [comment]
@tboerger this has been updated and should be good to go now

**Comment by donny-dont** [comment]
The Node folks have ignored PRs adding Windows images for ages from https://hub.docker.com/r/stefanscherer/node-windows/ so nope no Windows in this case.

**Comment by tboerger** [comment]
How should an official image be related to that?

**Comment by donny-dont** [comment]
@tboerger if there's no official image it seems unlikely that anyone would be building on Windows.

**Comment by tboerger** [comment]
And how do you connect a Docker image with general building and testing on Windows? The NPM plugin is not about Docker runtimes, it's about developing and testing on Windows.

**Pull request merged**
